# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.MainTable = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainTable.sizePolicy().hasHeightForWidth())
        self.MainTable.setSizePolicy(sizePolicy)
        self.MainTable.setMinimumSize(QtCore.QSize(800, 600))
        self.MainTable.setObjectName("MainTable")
        self.MainTable.setColumnCount(0)
        self.MainTable.setRowCount(0)
        self.verticalLayout.addWidget(self.MainTable)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.Menu = QtWidgets.QMenuBar(MainWindow)
        self.Menu.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.Menu.setDefaultUp(False)
        self.Menu.setNativeMenuBar(True)
        self.Menu.setObjectName("Menu")
        self.TasksMenu = QtWidgets.QMenu(self.Menu)
        self.TasksMenu.setObjectName("TasksMenu")
        self.ViewMenu = QtWidgets.QMenu(self.TasksMenu)
        self.ViewMenu.setObjectName("ViewMenu")
        MainWindow.setMenuBar(self.Menu)
        self.Status = QtWidgets.QStatusBar(MainWindow)
        self.Status.setObjectName("Status")
        MainWindow.setStatusBar(self.Status)
        self.AddTask = QtWidgets.QAction(MainWindow)
        self.AddTask.setObjectName("AddTask")
        self.ActualTasks = QtWidgets.QAction(MainWindow)
        self.ActualTasks.setObjectName("ActualTasks")
        self.CompletedTasks = QtWidgets.QAction(MainWindow)
        self.CompletedTasks.setObjectName("CompletedTasks")
        self.ViewMenu.addAction(self.ActualTasks)
        self.ViewMenu.addAction(self.CompletedTasks)
        self.TasksMenu.addAction(self.AddTask)
        self.TasksMenu.addAction(self.ViewMenu.menuAction())
        self.Menu.addAction(self.TasksMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Список задач"))
        self.TasksMenu.setTitle(_translate("MainWindow", "Задачи"))
        self.ViewMenu.setTitle(_translate("MainWindow", "Просмотр"))
        self.AddTask.setText(_translate("MainWindow", "Добавить"))
        self.ActualTasks.setText(_translate("MainWindow", "Актуальные"))
        self.CompletedTasks.setText(_translate("MainWindow", "Выполненные"))
