# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TaskDetailsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TaskDetailsWindow(object):
    def setupUi(self, TaskDetailsWindow):
        TaskDetailsWindow.setObjectName("TaskDetailsWindow")
        TaskDetailsWindow.resize(800, 450)
        TaskDetailsWindow.setMinimumSize(QtCore.QSize(400, 200))
        TaskDetailsWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        font = QtGui.QFont()
        font.setPointSize(10)
        TaskDetailsWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(TaskDetailsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.task_name = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.task_name.setFont(font)
        self.task_name.setText("")
        self.task_name.setObjectName("task_name")
        self.gridLayout_2.addWidget(self.task_name, 0, 0, 1, 5)
        self.task_details = QtWidgets.QTextBrowser(self.centralwidget)
        self.task_details.setObjectName("task_details")
        self.gridLayout_2.addWidget(self.task_details, 1, 0, 1, 5)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.clicks_label = QtWidgets.QLabel(self.centralwidget)
        self.clicks_label.setAlignment(QtCore.Qt.AlignCenter)
        self.clicks_label.setObjectName("clicks_label")
        self.verticalLayout.addWidget(self.clicks_label)
        self.click_button = QtWidgets.QPushButton(self.centralwidget)
        self.click_button.setObjectName("click_button")
        self.verticalLayout.addWidget(self.click_button)
        self.gridLayout_2.addLayout(self.verticalLayout, 2, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.null_button = QtWidgets.QPushButton(self.centralwidget)
        self.null_button.setObjectName("null_button")
        self.gridLayout.addWidget(self.null_button, 2, 1, 1, 1)
        self.start_pause_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_pause_button.setObjectName("start_pause_button")
        self.gridLayout.addWidget(self.start_pause_button, 2, 0, 1, 1)
        self.timer_label = QtWidgets.QLabel(self.centralwidget)
        self.timer_label.setAlignment(QtCore.Qt.AlignCenter)
        self.timer_label.setObjectName("timer_label")
        self.gridLayout.addWidget(self.timer_label, 0, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 4, 1, 1)
        self.close_task_button = QtWidgets.QPushButton(self.centralwidget)
        self.close_task_button.setObjectName("close_task_button")
        self.gridLayout_2.addWidget(self.close_task_button, 2, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 2, 3, 1, 1)
        TaskDetailsWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(TaskDetailsWindow)
        QtCore.QMetaObject.connectSlotsByName(TaskDetailsWindow)

    def retranslateUi(self, TaskDetailsWindow):
        _translate = QtCore.QCoreApplication.translate
        TaskDetailsWindow.setWindowTitle(_translate("TaskDetailsWindow", "Подробности задачи"))
        self.clicks_label.setText(_translate("TaskDetailsWindow", "0"))
        self.click_button.setText(_translate("TaskDetailsWindow", "Кликер"))
        self.null_button.setText(_translate("TaskDetailsWindow", "Обнулить"))
        self.start_pause_button.setText(_translate("TaskDetailsWindow", "Старт"))
        self.timer_label.setText(_translate("TaskDetailsWindow", "0"))
        self.close_task_button.setText(_translate("TaskDetailsWindow", "Завершить задачу"))
